# Generated by Django 5.1.2 on 2024-10-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
